name: Build and push Docker image

on:
  release:
    types: [published]
  workflow_dispatch:
env:
  CURRENT_VERSION: 27.0.3
  BUILD_NUMBER: 1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: gattipg
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Ubuntu 20.04 - Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: >
            gattipg/ubuntu-nvidia-dind:${{ env.CURRENT_VERSION }},
            gattipg/ubuntu-nvidia-dind:${{ env.CURRENT_VERSION }}-r${{ env.BUILD_NUMBER }},
            gattipg/ubuntu-nvidia-dind:latest
